CREATE DATABASE IF NOT EXISTS carbonlens;
USE carbonlens;

CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bills (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  bill_type VARCHAR(50) NOT NULL,
  consumption_value DOUBLE NOT NULL,
  consumption_unit VARCHAR(20) NOT NULL,
  co2_emitted DOUBLE NOT NULL,
  emission_level VARCHAR(20) NOT NULL,
  bill_date DATE NOT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
